version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    command: |
      sh -c "
      mkdir -p /mosquitto/config &&
      cat > /mosquitto/config/mosquitto.conf << 'EOF'
      listener 1883
      protocol mqtt
      
      listener 9001
      protocol websockets
      
      allow_anonymous true
      
      log_dest stdout
      log_type error
      log_type warning
      log_type notice
      log_type information
      log_timestamp true
      
      persistence true
      persistence_location /mosquitto/data/
      autosave_interval 1800
      
      max_connections 1000
      max_queued_messages 1000
      max_inflight_messages 20
      
      connection_messages true
      log_type subscribe
      log_type unsubscribe
      EOF
      mosquitto -c /mosquitto/config/mosquitto.conf
      "
    networks:
      - mosquitto-network

  mqtt-web-ui:
    image: vergissberlin/hivemq-mqtt-web-client
    container_name: mqtt-web-ui
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    networks:
      - mosquitto-network

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local

networks:
  mosquitto-network:
    driver: bridge
